spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: dev # 현재 활성화할 프로파일
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"


server:
  port: ${SERVER_PORT}

# 로깅 레벨 설정
logging:
  level:
    com.card.payment: DEBUG