spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: dev # 현재 활성화할 프로파일
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:wooricard_settlement}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always


server:
  port: ${SERVER_PORT:8082}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP:172.30.1.33}

# 로깅 레벨 설정
logging:
  level:
    com.card.payment: DEBUG